### PR TITLE
Add .editorconfig & cpu load test params

### PR DESCRIPTION
**Pull request by mingcheng**

### CODE REVIEW

**Comment by mingcheng** [comment]
usage: blade create cpu fullload --timeout 5 (in seconds)

**Comment by xcaspar** [comment]
> usage: blade create cpu fullload --timeout 5 (in seconds)

Great, this feature is exactly what we want to add, can you open an issue to associate this pr?

**Comment by mingcheng** [comment]
#9

**Comment by xcaspar** [comment]
> #9

Thank you for submitting the issue and pr. I have two questions here:

* The feature adapts the host to fail to respond the chaosblade tool invoked again, such as network blocking, memory leaks, and can we extract it to the upper layer as a generic capability?

* Direct stop process cannot change the status of the experiment, can we stop and modify the experiment status, similar to executing the destroy command?

**Comment by mingcheng** [comment]
updated :^p

**Comment by mingcheng** [comment]
By the way, add new feature `--cpu-num` param

**Comment by xcaspar** [comment]
> By the way, add new feature `--cpu-num` param

Awesome. Thank you again. Welcome you to join the project :-)

**Pull request merged**
