### PR TITLE
fixed build_with_linux on the macos

### LINKED ISSUE #359: Error, build_with_linux on the macos
## Issue Description
When I compiled with build_with_linux in macos, It reported an error of "make no target build_with"
Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. git checkout master branch
2. Run with " ARGS="cli os java" make build_with_linux"
3. 

### Tell us your environment
macos 10.15.4
Make 3.81

### PR DESCRIPTION
**Pull request by DLive**
### Describe what this PR does / why we need it
Fix build error, when compile with build_with_linux argument in macos.

### Does this pull request fix one issue?

Fixes #359

### Describe how you did it
1. add mirror to dockerfile
2. add volume to build_with target in the make file

### CODE REVIEW

**Comment by xcaspar** [comment]
@DLive Can you fix it based on master(v0.6.0) branch, because the makefile has been modified, so the compile checks have failed.

**Comment by DLive** [comment]
OK, I will submit a PR again.

**Comment by DLive** [comment]
@xcaspar 
  I check the pull request, it is updated of master branch. And Travis build error is because golang version needs to be greater than 1.13.
  I updated travis golang version to 1.14.3 and submitted, please review again.

Thanks!

**Comment by xcaspar** [comment]
@DLive Good job. Can you squash the commits to one, we should keep the commit trees clean. Thank you :-)

**Comment by DLive** [comment]
@xcaspar   The PR has completed squash the commits to one.
Thank you for your careful review.

**Pull request merged**
