### PR TITLE
add cli command server status

### PR DESCRIPTION
**Pull request by sunny0826**
### Describe what this PR does / why we need it
新增子命令 `server status`，主要用于部署到k8s上之后进行健康检查

### Describe how you did it
检测 server 进程以及运行端口

### Describe how to verify it
检查 server 进程是否存在，若存在则返回 up 状态以及 server 的端口号

### CODE REVIEW

**Comment by jianxingzhe** [comment]
why not use the readiness/liveness probe?

**Comment by xcaspar** [comment]
> why not use the readiness/liveness probe?

Can you introduce the details?

**Comment by jianxingzhe** [comment]
> > why not use the readiness/liveness probe?
> 
> Can you introduce the details?

in k8s，the pod liveness probe is used to check the server status. so if you want to deploy the blade server  in k8s, you can configure a liveness probe for the pod. if the liveness pod probe failed, the kubelet will restart the container automaticlly.  look the official doc for details: 
https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/

mybe, we should give a template for deploying the blade server in k8s.

**Comment by sunny0826** [comment]
> > > why not use the readiness/liveness probe?
> > 
> > 
> > Can you introduce the details?
> 
> in k8s，the pod liveness probe is used to check the server status. so if you want to deploy the blade server in k8s, you can configure a liveness probe for the pod. if the liveness pod probe failed, the kubelet will restart the container automaticlly. look the official doc for details:
> https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
> 
> mybe, we should give a template for deploying the blade server in k8s.

This PR usage:

```yaml
livenessProbe:
      exec:
        command:
        - /bin/sh
        - -ec
        - blade server status
```

**Comment by jianxingzhe** [comment]
> > > > why not use the readiness/liveness probe?
> > > 
> > > 
> > > Can you introduce the details?
> > 
> > 
> > in k8s，the pod liveness probe is used to check the server status. so if you want to deploy the blade server in k8s, you can configure a liveness probe for the pod. if the liveness pod probe failed, the kubelet will restart the container automaticlly. look the official doc for details:
> > https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
> > mybe, we should give a template for deploying the blade server in k8s.
> 
> This PR usage:
> 
> ```yaml
> livenessProbe:
>       exec:
>         command:
>         - /bin/sh
>         - -ec
>         - blade server status
> ```

you can use tcp liveness probe:
```yaml
 livenessProbe:
      tcpSocket:
        port: $blade_server_port
      initialDelaySeconds: 15
      periodSeconds: 20
```

**Comment by xcaspar** [comment]
@jianxingzhe It's a good idea for k8s env. but for non-k8s environments, this pr is also useful.

**Pull request merged**
