### PR TITLE
Simpify docker build: using go mod package manger and docker multi-stage builds.

### PR DESCRIPTION
**Pull request by mingcheng**
1. Using  official `go mod` for manage depends https://github.com/golang/go/wiki/Modules
2. Build Docker image with multi-stage builds by single Dockerfile(Suggest clean the old  for maintain issues).

### CODE REVIEW

**Comment by mingcheng** [comment]
With issues #16

**Comment by xcaspar** [comment]
Thank you for improving the compile and the package manager of the project.

I just found out that the email used by your submission does not match your github email, which causes it to not be displayed in contributor page. You need to modify the email address used to submit .

**Comment by mingcheng** [comment]
I did it deliberately for privacy reasons :-p

**Comment by xcaspar** [comment]
> I did it deliberately for privacy reasons :-p

We don't ask for sign-off now, so even if you add your github email, no one will know it. 
Confirm again,  are you sure not to modify?

**Comment by mingcheng** [comment]
Yes, just read the code. I will modify my github mail address if necessary in future.

**Comment by xcaspar** [comment]
> Yes, just read the code. I will modify my github mail address if necessary in future.

OK, I will review the PR later. Thank you again 😄

**Comment by xcaspar** [comment]
> 1. Using  official `go mod` for manage depends https://github.com/golang/go/wiki/Modules
> 2. Build Docker image with multi-stage builds by single Dockerfile(Suggest clean the old  for maintain issues).

The `go mod` feature was added after the golang 1.11 release, it's a new feature, so may contains some bugs . Although it no longer relies on GOPATH, but it's not better than `govendor` tool in practical use, so I recommend to use the current `govendor` as the package manager.

**Comment by xcaspar** [comment]
The commit for simpifying docker build with multi-stage builds is OK. :-)

**Comment by xcaspar** [comment]
There is no problem with the submission of the global timeout feature. So only the package manager problem. Thank you.

**Comment by mingcheng** [comment]
You can both use `govendor` and `go mod`, it's not conflicting. The `go mod` package manager works only `go.mod` file exists, and consider its official support in future.

**Comment by mingcheng** [comment]
Oh, I forgot this PR is including global `timeout` param support. I will push PR with new branch at next time, sorry.

**Comment by xcaspar** [comment]
> You can both use `govendor` and `go mod`, it's not conflicting. The `go mod` package manager works only `go.mod` file exists, and consider its official support in future.

OK, I will keep the file.

**Pull request merged**
